### PR TITLE
DeepStateFrontend API support for front-ends

### PR DESCRIPTION
**Pull request by ex0dus-0x**
Initial work (definitely not complete, needs feedback) in adding a base object for creating fuzzer front-ends. 

Base functionality includes discovering path to fuzzer and compiler for instrumentation, and constructing a basic command for CLI execution with `subprocess.call`. Also provides generic interface to parse command line arguments.

### TODO

* [x] Align code style to rest of codebase
* [x] More robust way for user to collect args and transform into CLI command (?)
* [x] Use `DeepStateFrontend` to re-write Eclipser front-end

### CODE REVIEW

**Comment by agroce** [comment]
At a high level, looks sensible to me

**Comment by agroce** [comment]
Either bake test extraction into execute_fuzzer or have an explicit post_processing step?  I'm wondering if we might want to separate, since if we're doing ensemble stuff, we might not want to slow down to do expensive extractions (Eclipser can take quite a while) on everything we eventually want to pull out, just do it on new seeds or something, more fine-grained...

**Comment by ex0dus-0x** [comment]
Front-end base API is in a working state and ready for review!

Not entirely sure how to approach ensemble-based fuzzing with this front-end API. We could (possibly into another PR)  implement a `deepstate-ensemble` executable, which imports available fuzzer front-ends, executes and monitors fuzzing jobs, and synchronize seeds to a shared pool. We could probably implement an `ensemble()` method for front-ends that performs the logic for determining interesting seeds, while leaving `post_processing()` for any other user tasks like test decoding.

**Comment by agroce** [comment]
Ensemble in separate PR seems fine by me.  I'm swamped for review for a little bit.  Have you checked if the docker builds and runs the eclipser example from the blog post this way?  Seems like a good shakedown test...

**Comment by ex0dus-0x** [comment]
The docker build was successful and `deepstate-eclipser` was able to produce a crashing input, as per the blog post.

**Comment by agroce** [comment]
Great.  Merging.

**Pull request merged**
