### PR TITLE
Additional tests and checks for existing tests

### PR DESCRIPTION
**Pull request by agroce**
Adds CI tasks (and regression tests) for all examples except Squares and Euler (these are omitted due to extremely long execution time with angr).

### CODE REVIEW

**Comment by agroce** [comment]
Maybe I'm missing something, but the only purpose of the travis.yml stuff is:

1) to let us run things in nosetests during a regresson run outside Travis that don't run in time for a Travis job

2) to control parallelization of the Travis jobs -- the test only runs the part specified by the current environment variable

It'd be better to split them up into multiple tests, for normal nose, like I did with TSTL, but for CI (which really gets run more often), it's nice not to have the effort of multiple commands or a bunch of spurious non-run tests reported as passing.  But there's probably a better way to do it.

**Comment by agroce** [comment]
The goal is just:

- in travis we get a task for each example/test

- outside travis we can run everything

But the current lack of breakdown IS lousy outside travis.

**Comment by agroce** [comment]
I guess the right thing is to drop environment vars from the python tests, and add a bunch of ifs that run different nosetests selections based on the env variables.

**Comment by agroce** [comment]
Should we hold off on merging this until it's refactored?  It won't change the value for CI testing, but is more of a long-term maintenance change.  I'd be inclined to get in a passing (I think) set of working tests, then I'll refactor to something cleaner once I think about it.

We could use files to store expectations, eventually, but I want more than just text matching, so it'd need a little language.

**Comment by pgoodman** [comment]
@agroce I have refactored the code according to what I had in mind. I probably did something wrong (e.g. [this error](https://travis-ci.org/trailofbits/deepstate/jobs/405359714#L1649)).

I also gave my hand at fixing the lack of symbolic malloc support in Manticore for the double reversal of vectors by having it pre-allocate a fixed amount, then resize the container to a symbolic size less-than-or-equal to the fixed size. Pumping would have also worked, though I don't seem to have a minimize function for `uint64_t`s.

**Comment by agroce** [comment]
I'll take a look at the refactor, see if I can figure out the error.  Thanks!

**Comment by agroce** [comment]
Aha!  The bug is that if you name a function run_test, nosetests thinks it's a test.  I thought it was just for "test_foo" but no.  Fixing now.

**Comment by agroce** [comment]
(I think it's still not going to do quite what we want, but I can get it there maybe pretty quickly)

**Comment by agroce** [comment]
Peter, I think the tests should be ok now, except Lists still fails (you can see the issue) and Arithmetic may be so long-running it times out, depending on how fast manticore is.

**Comment by agroce** [comment]
To add a test, now, you

- add a test_whatever file inheriting from deepstate_base like the current tests

- add a task and run for it in .travis.yml

The second step I can't really figure a way around since we need the parallelism to avoid timeouts.

**Comment by agroce** [comment]
arithmetic is (barely) fast enough, so that's good.

**Comment by agroce** [comment]
takeover and lists fail, and the failures look like real failures.  Otherwise, all ok, so I think we have a good set of basic tests for now.

**Pull request merged**
